version: "{branch}-{build}"
image: Visual Studio 2017
install:
- curl -sSf -o rustup-init.exe https://win.rustup.rs/
- rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain stable
- set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
- rustc -Vv
- cargo -V
build_script:
- git config core.symlinks true
- ps: rm -r datasets
- git submodule update --init --recursive
- git reset --hard
- cd cli
- cargo build --verbose --release
test_script:
- cargo test --verbose
artifacts:
- name: askalono.exe
  path: 'target\release\askalono.exe'
deploy:
  provider: GitHub
  artifact: askalono.exe
  description: ''
  auth_token:
    secure: GmC3HJHS4wRFx3drrsEa16+xIxGO6HZLDn+h3CuLLKldUm9VT3WMOj/ZXtva6Soe
  on:
    appveyor_repo_tag: true