language: rust
rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly

cache: cargo

script:
    - git submodule update --init
    - cargo build --verbose --all
    - cargo test --verbose --all
    # TODO: --release, strip, push to GH releases