[package]
name = "askalono"
version = "0.3.0"
description = "a library to detect the contents of license files"
license = "Apache-2.0"
repository = "https://github.com/amzn/askalono"
authors = ["Jacob Peddicord <peddicor@amazon.com>"]
readme = "README.md"
exclude = [
    "/scripts/**/*",
    "/.github/**/*",
    "/license-list-data/**/*",
]

[dependencies]
failure = "0.1.1"
lazy_static = "1.0.0"
log = "0.4.1"
regex = "0.2.10"
rmp-serde = "0.13.7"
serde = "1.0.33"
serde_derive = "1.0.33"
unicode-normalization = "0.1.5"

# spdx deps
serde_json = { version = "1.0.11", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
flate2 = "1.0.1" # TODO: this should be fine in wasm soon
rayon = "1.0.1"

[dev-dependencies]
env_logger = "0.5.5"

[workspace]
members = ["cli"]
exclude = ["wasm"]

[lib]
name = "askalono"
path = "src/lib.rs"

[features]
default = ["spdx"]
spdx = ["serde_json"]
