[package]
name = "askalono-cli"
version = "0.1.0"
authors = ["Jacob Peddicord <peddicor@amazon.com>"]

[dependencies]
askalono = { path = "../" }
clap = { version = "2.26.2", features = ["yaml"] }
difference = "1.0"
env_logger = "0.4.3"
log = "0.3"
rayon = "0.8.2"

[build-dependencies]
askalono = { path = "../" }

[features]
default = ["embedded-cache"]
embedded-cache = []
