[package]
name = "askalono-cli"
version = "0.1.0"
description = "a tool to detect the contents of license files"
license = "Apache-2.0"
repository = "https://github.com/amzn/askalono"
authors = ["Jacob Peddicord <peddicor@amazon.com>"]
readme = "../README.md"
exclude = [
    "/embedded-cache.bin.gz"
]

[dependencies]
askalono = { version = "0.1.0", path = "../" }
clap = { version = "2.26.2", features = ["yaml"] }
difference = "1.0"
env_logger = "0.4.3"
log = "0.3"
rayon = "0.8.2"

[build-dependencies]
askalono = { version = "0.1.0", path = "../" }

[[bin]]
name = "askalono"
path = "src/main.rs"

[features]
default = ["embedded-cache"]
embedded-cache = []
